"""initial schema

Revision ID: 20260605_0001
Revises:
Create Date: 2026-06-05
"""

from alembic import op
import sqlalchemy as sa

revision = "20260605_0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.create_table("departments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("name", sa.String(120), nullable=False, unique=True), sa.Column("manager_id", sa.Integer()), sa.Column("parent_id", sa.Integer()), sa.Column("status", sa.String(32), nullable=False, server_default="active"))
    op.create_table("users", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("open_id", sa.String(120), unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("department_id", sa.Integer(), sa.ForeignKey("departments.id")), sa.Column("title", sa.String(120)), sa.Column("status", sa.String(32), nullable=False, server_default="active"))
    op.create_foreign_key("fk_departments_manager", "departments", "users", ["manager_id"], ["id"])
    op.create_foreign_key("fk_departments_parent", "departments", "departments", ["parent_id"], ["id"])
    op.create_table("roles", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(80), nullable=False, unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("description", sa.Text()))
    op.create_table("permissions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(120), nullable=False, unique=True), sa.Column("name", sa.String(120), nullable=False), sa.Column("description", sa.Text()))
    op.create_table("user_roles", sa.Column("user_id", sa.Integer(), sa.ForeignKey("users.id"), primary_key=True), sa.Column("role_id", sa.Integer(), sa.ForeignKey("roles.id"), primary_key=True))
    op.create_table("role_permissions", sa.Column("role_id", sa.Integer(), sa.ForeignKey("roles.id"), primary_key=True), sa.Column("permission_id", sa.Integer(), sa.ForeignKey("permissions.id"), primary_key=True))
    op.create_table("strategic_goals", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(80), nullable=False, unique=True), sa.Column("name", sa.String(200), nullable=False), sa.Column("description", sa.Text()), sa.Column("year", sa.Integer(), nullable=False), sa.Column("progress", sa.Integer(), nullable=False, server_default="0"), sa.Column("status", sa.String(32), nullable=False, server_default="active"))
    op.create_table("parent_tasks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(80), nullable=False, unique=True), sa.Column("title", sa.String(240), nullable=False), sa.Column("description", sa.Text()), sa.Column("goal_id", sa.Integer(), sa.ForeignKey("strategic_goals.id"), nullable=False), sa.Column("department_id", sa.Integer(), sa.ForeignKey("departments.id"), nullable=False), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("priority", sa.String(32), nullable=False, server_default="normal"), sa.Column("status", sa.String(32), nullable=False, server_default="in_progress"), sa.Column("progress", sa.Integer(), nullable=False, server_default="0"), sa.Column("due_date", sa.Date()), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("department_tasks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(80), nullable=False, unique=True), sa.Column("title", sa.String(240), nullable=False), sa.Column("parent_task_id", sa.Integer(), sa.ForeignKey("parent_tasks.id"), nullable=False), sa.Column("department_id", sa.Integer(), sa.ForeignKey("departments.id"), nullable=False), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="in_progress"), sa.Column("progress", sa.Integer(), nullable=False, server_default="0"), sa.Column("due_date", sa.Date()))
    op.create_table("sub_tasks", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(80), nullable=False, unique=True), sa.Column("title", sa.String(240), nullable=False), sa.Column("department_task_id", sa.Integer(), sa.ForeignKey("department_tasks.id"), nullable=False), sa.Column("executor_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="pending_update"), sa.Column("progress", sa.Integer(), nullable=False, server_default="0"), sa.Column("risk_level", sa.String(32), nullable=False, server_default="none"), sa.Column("due_date", sa.Date()))
    op.create_table("weekly_updates", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("sub_task_id", sa.Integer(), sa.ForeignKey("sub_tasks.id"), nullable=False), sa.Column("week_key", sa.String(20), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="draft"), sa.Column("progress", sa.Integer(), nullable=False, server_default="0"), sa.Column("this_week", sa.Text()), sa.Column("next_week", sa.Text()), sa.Column("risk", sa.Text()), sa.Column("needs_coordination", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("submitter_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("submitted_at", sa.DateTime(timezone=True)), sa.UniqueConstraint("sub_task_id", "week_key", name="uq_weekly_update_subtask_week"))
    op.create_table("weekly_update_revisions", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("weekly_update_id", sa.Integer(), sa.ForeignKey("weekly_updates.id"), nullable=False), sa.Column("editor_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("snapshot", sa.JSON(), nullable=False), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("task_events", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("object_type", sa.String(60), nullable=False), sa.Column("object_id", sa.Integer(), nullable=False), sa.Column("event_type", sa.String(80), nullable=False), sa.Column("title", sa.String(240), nullable=False), sa.Column("content", sa.Text()), sa.Column("actor_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("risk_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("code", sa.String(80), nullable=False, unique=True), sa.Column("sub_task_id", sa.Integer(), sa.ForeignKey("sub_tasks.id"), nullable=False), sa.Column("level", sa.String(32), nullable=False), sa.Column("description", sa.Text(), nullable=False), sa.Column("status", sa.String(32), nullable=False, server_default="open"), sa.Column("created_by_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("coordination_items", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("sub_task_id", sa.Integer(), sa.ForeignKey("sub_tasks.id"), nullable=False), sa.Column("title", sa.String(240), nullable=False), sa.Column("description", sa.Text()), sa.Column("status", sa.String(32), nullable=False, server_default="open"), sa.Column("owner_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("notification_records", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("target_user_id", sa.Integer(), sa.ForeignKey("users.id"), nullable=False), sa.Column("notification_type", sa.String(80), nullable=False), sa.Column("related_type", sa.String(60)), sa.Column("related_id", sa.Integer()), sa.Column("title", sa.String(240), nullable=False), sa.Column("web_url", sa.String(500)), sa.Column("send_status", sa.String(32), nullable=False, server_default="mock_sent"), sa.Column("clicked", sa.Boolean(), nullable=False, server_default=sa.false()), sa.Column("result", sa.String(200)), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))
    op.create_table("attachments", sa.Column("id", sa.Integer(), primary_key=True), sa.Column("filename", sa.String(240), nullable=False), sa.Column("storage_path", sa.String(500), nullable=False), sa.Column("related_type", sa.String(60), nullable=False), sa.Column("related_id", sa.Integer(), nullable=False), sa.Column("uploader_id", sa.Integer(), sa.ForeignKey("users.id")), sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.func.now()))


def downgrade() -> None:
    for table in ["attachments", "notification_records", "coordination_items", "risk_records", "task_events", "weekly_update_revisions", "weekly_updates", "sub_tasks", "department_tasks", "parent_tasks", "strategic_goals", "role_permissions", "user_roles", "permissions", "roles", "users", "departments"]:
        op.drop_table(table)
